### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by flagsoft**

### CODE REVIEW

**Comment by kwbock** [comment]
Thanks for adding these steps to the readme. I've merged this into master.

**Comment by flagsoft** [comment]
Thank you! - I also noted a "but". Just when I resize the Window over a button, the text will disappear. Dont know why, was not able to fix it.

**Comment by kwbock** [comment]
So if you resize a window so that it is smaller than the button itself but some of the button is visible then the button text disappears?

**Comment by flagsoft** [comment]
Yes. I did a movie for you, so that you can see to bug: http://flagsoft.com/public/ui-bug.mov

**Comment by flagsoft** [comment]
BTW: Mac OS 10.8.2 (newest), Version 4.6 (4H127) (newest).

**Comment by kwbock** [comment]
Thanks, I'll try to take a look at that this weekend. I think it may have something to do with the bounds checking. Are you using or thinking about using these buttons in a project? If so I'd love to hear about it.

**Comment by flagsoft** [comment]
Maybe... I just was looking for how to do my own UI element with Xcode / Cocoa... and it seems to be hard...

**Comment by kwbock** [comment]
It's not the easiest thing, but I adapted this from an iOS control that produced a similarly styled button. Certain controls are easier to subclass and customized than others.

**Pull request merged**
